Cycle Detection and Removal in Linkedlist file added
MakeContributions/DSA pull request #1022
Opened 2022-10-12 15:08 UTC by seemanttripathi

**PR Checklist:**
- [x ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Name - Cycle Detection and Removal
Language - Python

**Other information:**

2022-10-12 15:10 UTC, seemanttripathi commented
cycle detection and removal in linkedlist in Python #1003
I have solved this problem via this pull request

2022-10-17 07:17 UTC, Arsenic-ATG requested changes
1. the checks are failing due to a some other code in the main repository which have been fixed after 0c08f6562466e6311058c1ae2201b07c56caffa2 , please update your fork accordingly.
2. Every addition of a new algorithm to the repository should also be accompanied by updating the corresponding index README.md file with a link to the file in it.

2022-10-19 19:34 UTC, seemanttripathi commented
I have updated the README.md file ..
Could you please check and approve

2022-10-20 12:09 UTC, Arsenic-ATG approved these changes

2022-10-21 02:48 UTC, merged