Prefix-to-Postfix added in stack assignment
MakeContributions/DSA pull request #1026
Opened 2022-10-13 10:13 UTC by roohan25

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-10-16 00:47 UTC, ming-tsai commented
Hi @roohan25,
Please rename the file from `Prefix-to-postfix-using-stack1.c` to `Prefix-to-postfix-using-stack.c`

2022-10-16 03:26 UTC, roohan25 commented
The requested changes have been updated, Please check once and if any query exist, do reach out , will be happy to resolve the issue .

2022-10-20 12:48 UTC, mohitchakraverty requested changes
Please make fix the following typo and also update your respective README
In your case it will be - algorithms/C/README.md

2022-10-20 12:48 UTC, mohitchakraverty commented on algorithms/C/stacks/Prefix-to-postfix-using-stack.c
> +            //concating the operands and operator
```suggestion
            //concatenating the operands and operator
```

2022-12-28 16:46 UTC, closed without merging