Change dijksta algorithm for better memory usage
MakeContributions/DSA pull request #1061
Opened 2022-10-21 11:35 UTC by Denisthatorf

https://github.com/MakeContributions/DSA/issues/1058 - try to fix this problem
I optimize the Dijkstra algorithm in C++ 

The Dijkstra algorithm uses vector<vector<pair<int,int>>> graph(V+1,vector<pair<int,int>>()) as a matrix. This is very, very bad for memory, because the vector in the vector in memory is not stored linearly, and can be scattered in memory very much. As an alternative, I propose to use a regular array (data = new T [rows * columns]) allocated on the heap and get its elements like this : *(_data + row * _rows + column).

2022-10-25 07:53 UTC, Arsenic-ATG requested changes
typos causing codespell check to fail 

```
./algorithms/CPlusPlus/Graphs/dijkstra.cpp:4: recomend ==> recommend
./algorithms/CPlusPlus/Graphs/dijkstra.cpp:85: recomend ==> recommend
```

2022-10-25 07:53 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Graphs/dijkstra.cpp
> +//I highly recomend to create matrix class
```suggestion
//I highly recommend to create matrix class
```

2022-10-25 07:53 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Graphs/dijkstra.cpp
> +    //I highly recomend to create matrix class
```suggestion
    //I highly recommend to create matrix class
```

2022-10-26 10:43 UTC, Denisthatorf commented
Can you check one more time?

2022-10-30 16:02 UTC, merged