Largest and smallest number in an array (C++)
MakeContributions/DSA pull request #1110
Opened 2022-12-20 08:41 UTC by Uma-95

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer to the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x ] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [x ] Other, please describe:

**Briefly describe the changes in this PR**
This is a simple program that is used to find the smallest and largest numbers in an array using sort function of C++ STL library.

**Other information:**
For sort function:
Time Complexity: O(N log N)
Auxiliary Space: O(1)

2022-12-20 08:45 UTC, Uma-95 commented
@RK-Shandilya I'm contributing to a repository for the first time. Kindly review my PR. Looking forward to your feedback.

2022-12-20 08:49 UTC, Uma-95 commented
This is my first time contributing to a repository which is why I chose to add a simple program to this repository.
Kindly review my PR and I'm looking forward to some feedback.
@Arsenic-ATG @UG-SEP @aayushjain7 @Ashborn-SM @Ashad001

2022-12-21 12:03 UTC, Arsenic-ATG requested changes
Apart from the review suggest in review comments, it is also mandatory to update corresponding index README.md file ( `algorithms/CPlusPlus/README.md` in your case ) with an entry of your program in it.

look at a successfully merged pull request to see how it's done.

2022-12-21 12:03 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Arrays/Largest and Smallest Number in an array.cpp
> +//the first element would be the smallest and the last elemnet would be the largest
I don't know how it actually went under the codespell's radar, but spelling of element is wrong here.

```suggestion
//the first element would be the smallest and the last element would be the largest
```

2022-12-22 03:14 UTC, Arsenic-ATG approved these changes

2022-12-22 13:29 UTC, merged