Create string_reverse.cpp
MakeContributions/DSA pull request #113
Opened 2021-03-18 20:04 UTC by hazel11182

Reversing a string

2021-03-19 04:47 UTC, Arsenic-ATG requested changes
on top of review comment left in the file, the [changes requested on your other PR](https://github.com/MakeContributions/DSA/pull/114#pullrequestreview-616053363) also imply here.

2021-03-19 04:47 UTC, Arsenic-ATG commented on strings/c-or-cpp/string_reverse.cpp
> +#include<cstring>
std::string is declared in `<string>` header and not in `<cstring>`.

2021-03-23 00:00 UTC, ming-tsai commented
Please check it again @Arsenic-ATG

2021-03-23 07:45 UTC, Arsenic-ATG commented
@ming-tsai , she have just fixed one of the errors pointed out by me. 

she still have to add the program to index Readme.md and also change the naming convention to include hyphens"-" instead of underscores"_" in the name, as mentioned in contribution guidelines.

2021-03-24 13:27 UTC, hazel11182 reviewed
done. how do i add it to the readme index?

2021-03-26 06:16 UTC, Arsenic-ATG approved these changes

2021-03-26 14:06 UTC, ming-tsai commented
Hi @hazel11182,
Nice work, thanks for your contributions, and welcome to our team.
> The invitation [link](https://github.com/MakeContributions)

2021-03-26 14:06 UTC, merged