Create sqrt_monotonic_binary_search.cpp
MakeContributions/DSA pull request #114
Opened 2021-03-18 20:30 UTC by hazel11182

2021-03-18 20:33 UTC, TawfikYasser commented
Please explain what is this code do? @hazel11182

2021-03-18 20:36 UTC, hazel11182 commented
we are finding the squareroot of any given given number  till 3 decimals using binary search. and we applied the concept of binary search in monotonic functions.

2021-03-18 20:39 UTC, hazel11182 commented
@ming-tsai now is it fine?

2021-03-18 20:43 UTC, ming-tsai commented
Hi @Arsenic-ATG,
Could help me on this pull request?

2021-03-18 20:45 UTC, ming-tsai commented
> @ming-tsai now is it fine?

Could you explain me what will be the difference between binary search on monotonic function and normal binary search?

2021-03-19 04:16 UTC, Arsenic-ATG commented
> Could you explain me what will be the difference between binary search on monotonic function and normal binary search?

@ming-tsai there is no difference in this case. 

it is one of the used cases where binary search will be a viable option to choose as linear search will take tremendous amount of time to do the same task.

although a program is already there implanting a classical binary search on a list or array of discrete items, but this is also a nice used case where binary search is being used on continuous set of values ( example where `target_value` belongs to closed interval [0,n] ) instead of discrete set of values ( for example where `target_value` belongs to { 1 , 4, 5 ,12 , 15 } ).

2021-03-19 04:29 UTC, Arsenic-ATG requested changes
the program functionally works ✅
 
but you forgot some minor things :- 

-  updating the [index readme file](https://github.com/MakeContributions/DSA/blob/main/searching/README.md) with your creation in the list 

- prefer using `-` as word separator instead of under-sore(`_`)

all of this is already mentioned in the [repository's contribution guidelines](https://github.com/MakeContributions/DSA#1-contribution-specifications) which is where you should go for further details about the same.

2021-03-19 07:25 UTC, hazel11182 commented
@Arsenic-ATG what needs to be done now?

2021-03-19 07:30 UTC, Arsenic-ATG commented
> @Arsenic-ATG what needs to be done now?

just perform the required changes on your forked branch (https://github.com/hazel11182/DSA/tree/patch-3), the changes would be automatically reflected back to this pull request.

2021-03-24 13:25 UTC, hazel11182 commented
done

2021-03-24 23:49 UTC, ming-tsai commented on searching/c-or-cpp/sqrt_monotonic_binary_search.cpp
> +#include <iostream>
Hi @hazel11182,
Could replace the file name from **_** to **-**?

2021-03-26 06:32 UTC, Arsenic-ATG commented
> done

@hazel11182 I think you got it wrong, we are talking about the name of the file you created ( [sqrt_monotonic_binary_search.cpp](https://github.com/hazel11182/DSA/blob/patch-3/searching/c-or-cpp/sqrt_monotonic_binary_search.cpp) ) and not the title of the pull request. 

and [this](https://github.com/hazel11182/DSA/blob/patch-3/searching/README.md) is your index file that you have to add your program to at the end of the list under `c  or cpp` section with a relative link to your code file. 

I have done the required changes for you in the [other pull request](https://github.com/MakeContributions/DSA/pull/113) and you make take reference from that about how this should be done.


-----

P.S. 
if you don't know how to make a text a hyperlink then use the following syntax 
```
[text](https://github.com/MakeContributions/DSA/pull/114)
```
which will look like this 

[text](https://github.com/MakeContributions/DSA/pull/114)


**you may look at [this](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files) guide for more information about creating relative links in any markdown file.**

----

2021-04-02 10:19 UTC, Arsenic-ATG commented
###  🚧 closing this PR because of long inactivity. 

If someone want to work on this then feel free to reopen it or create a new PR with the required changes.

2021-04-02 11:23 UTC, hazel11182 commented
How do i reopen PR?

On Fri, 2 Apr 2021 at 3:50 PM, Arsenic ***@***.***> wrote:

> Closed #114 <https://github.com/MakeContributions/DSA/pull/114>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MakeContributions/DSA/pull/114#event-4545230934>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKMEBPAPP623MELZAYJWTTLTGWK5HANCNFSM4ZNK4QIQ>
> .
>

2021-04-02 12:41 UTC, hazel11182 commented
HI, sorry for being inactive. I have resolved the file name. Is it nowfine?

2021-04-02 16:16 UTC, Arsenic-ATG submitted a review, later dismissed

2021-04-02 16:20 UTC, Arsenic-ATG commented
This PR will conflict with Pr #127 as both upgrade readme files.

2021-04-02 17:43 UTC, ming-tsai commented
I will create merge with both pr

2021-04-02 18:05 UTC, merged

2021-04-02 18:06 UTC, ming-tsai approved these changes