pull request
MakeContributions/DSA pull request #236
Opened 2021-04-19 18:53 UTC by goelRagga

2021-04-19 19:14 UTC, ming-tsai commented
Hi @goelRagga,
Two suggestions before @Arsenic-ATG check this pull request:
1. Please update your branch with our main, and move your `.cpp` file to [here](https://github.com/MakeContributions/DSA/tree/main/algorithms/CPlusPlus)
2. If you want to add documentations, please add to [here](https://github.com/MakeContributions/DSA/tree/main/docs/en)

2021-04-20 08:56 UTC, aayushjain7 approved these changes

2021-04-21 03:18 UTC, Arsenic-ATG requested changes
This program already exist in the repository ([here](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/Trees/count-and-sum-of-nodes-in-binary-tree.cpp))

As already pointed out by @ming-tsai , the repository structure has been changed and now all the algorithms are housed in `./algorithms/<Language>`. 

You can learn more about in issue #219 .

2021-04-21 03:50 UTC, ming-tsai commented
Close due to is duplicated

2021-04-21 03:50 UTC, closed without merging