Create Merge Sort Documentation
MakeContributions/DSA pull request #246
Opened 2021-04-21 17:21 UTC by TawfikYasser

Hi

This PR closes #245 

It is my first step in docs.

Thanks

2021-04-21 18:45 UTC, ming-tsai requested changes
Hi @TawfikYasser,
Nice work, I just add some comments

2021-04-21 18:45 UTC, ming-tsai commented on docs/en/Sorting/MergeSort.md
> +* Java: [@TawfikYasser](https://github.com/TawfikYasser)
Does this part is necessary?
Remember we have use git for control version

2021-04-21 18:45 UTC, ming-tsai commented on docs/en/Sorting/MergeSort.md
> +# Merge Sort
Could you rename the file's name to `Merge-Sort.md`, after that add it on [README.md](https://github.com/TawfikYasser/DSA/tree/main/docs/en)

2021-04-24 19:02 UTC, ming-tsai commented
Hi @TawfikYasser,
Are you actvie?

2021-04-24 23:38 UTC, ming-tsai approved these changes
Nice work @TawfikYasser

2021-04-24 23:39 UTC, ming-tsai approved these changes

2021-04-24 23:39 UTC, merged

2021-04-25 01:07 UTC, TawfikYasser commented
@ming-tsai  Sorry but I'm very busy these days. Thanks for fixing the issue.