add fold-linked-list
MakeContributions/DSA pull request #266
Opened 2021-04-26 13:53 UTC by kartickg33

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-04-26 15:45 UTC, aayushjain7 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +}
Node constructer is missing.

2021-04-26 15:46 UTC, aayushjain7 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +}
Also, give a description of the question at top of the file before starting the program.

2021-04-26 15:46 UTC, aayushjain7 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +}
Write the output of the program also.

2021-04-26 15:48 UTC, aayushjain7 requested changes
Also, update the README.md file of the Java folder,

2021-04-26 17:21 UTC, kartickg33 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +}
Updated as required.

2021-04-26 19:08 UTC, aayushjain7 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +}
set for next also
`this.next = null`

2021-04-26 19:10 UTC, aayushjain7 requested changes

2021-04-26 19:10 UTC, aayushjain7 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +        this.data = data;
set for next also,
`this.next = null;`

2021-04-26 19:18 UTC, kartickg33 commented on algorithms/Java/linked-lists/fold-linked-list.java
> +        this.data = data;
updated

2021-04-27 08:50 UTC, aayushjain7 approved these changes
Nice work! 👍🏼

2021-04-28 13:24 UTC, kartickg33 commented
Please review my PR

2021-04-28 13:56 UTC, merged