Add bubble sorting for C language
MakeContributions/DSA pull request #269
Opened 2021-04-26 19:57 UTC by nasdev-cmd

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Bubble sort for C language: https://onlinegdb.com/SJeYlj94wO

**Other information:**

2021-04-27 12:12 UTC, Arsenic-ATG submitted a review, later dismissed

2021-04-27 13:17 UTC, UG-SEP commented on algorithms/C/sorting/bubble-sort.c
> +//time complexity: O(n^2)
```suggestion
It is better if you add time complexity at the beginning or end of the program
```

2021-04-27 13:18 UTC, UG-SEP commented on algorithms/C/sorting/bubble-sort.c
> +}
please give a example at the end of the program i.e. input 
                                                                                    output

2021-04-27 13:22 UTC, UG-SEP requested changes
Kindly make the changes
Feel free to ask doubt

2021-04-27 17:50 UTC, UG-SEP approved these changes
@nasdev-cmd Thanks for contributing 😀
We glad to have a contributor like you 😊
Hope you contribute more to this project 🤞🤞

2021-04-27 17:52 UTC, UG-SEP commented
@ming-tsai please check it

2021-04-27 17:53 UTC, nasdev-cmd commented
@UG-SEP Thanks, I look forward to collaborating with you!

2021-04-27 17:54 UTC, UG-SEP commented
> @UG-SEP Thanks, I look forward to collaborating with you!

Sure

2021-04-29 15:34 UTC, Arsenic-ATG approved these changes

2021-04-29 15:35 UTC, merged