linear search in c
MakeContributions/DSA pull request #293
Opened 2021-05-12 04:43 UTC by arpitgoyal27

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-05-12 13:43 UTC, UG-SEP requested changes
Hey @arpitgoyal27  do close the PR only  done the changes GitHub automatically add the changes in PR

2021-05-12 13:43 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +#define SIZE 100  //change according to question
take size from the user so memory waste can be prevented and think if the size>100 then the program will terminate

2021-05-12 13:43 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +      data[ i ] = 2 * i;
what this you have to take array value from the user

2021-05-12 13:43 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +   int data[ SIZE ], i, temp;
```suggestion
int *data,i,temp;
data=(int*)malloc(sizeof(int)*size);
```

2021-05-12 13:43 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +   int searchQuery; //value to search in the array
it would be better if you initialize it above

2021-05-12 13:43 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +      printf("Found value in element %d.", temp);
```suggestion
      printf("Found value in element %d", temp);
```

2021-05-12 13:43 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +      printf("Value not found.");
```suggestion
      printf("Value not found");
```

2021-05-12 14:46 UTC, ming-tsai commented
Hi @arpitgoyal27,
Do not close your pull request when update it

2021-05-13 13:55 UTC, UG-SEP requested changes
please do the change else everything looks  good

2021-05-13 13:55 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +      printf("Found value and the index is :%d", temp);
```suggestion
      printf("Value found at index no: %d", temp);
```
your sentence has not perfect sense

2021-05-13 13:55 UTC, UG-SEP commented on algorithms/C/searching/linearsearch.c
> +   scanf("%d",&size);
please add the UI here 
Hint: printf("Enter size: ");
So the user can understand that what to do

2021-05-14 16:01 UTC, UG-SEP approved these changes
Thanks for contributing @arpitgoyal27 
Hope you contribute more to this project

2021-05-15 11:22 UTC, merged