Create heap-sort.py
MakeContributions/DSA pull request #298
Opened 2021-05-13 10:35 UTC by Sranu2109

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Other information:**

Created heap sort in python.

2021-05-13 13:48 UTC, sridhar-5 commented
I'm checking it now.

2021-05-13 14:56 UTC, sridhar-5 requested changes
check the comments I've mentioned and do the changes accordingly. if you have trouble again. please comment I would be happy to help here.

2021-05-13 14:56 UTC, sridhar-5 commented on algorithms/Python/sorting/heap-sort.py
> +alist = [int(x) for x in alist]
There is a failing test that is pointing to this line. I think replacing the line 40 with the snippet below might solve this.

if you still have a failing test please comment.

alist = [x for x in alist]
alist = list(map(int, alist))

2021-05-14 10:09 UTC, sridhar-5 commented
Not really sure why test fails all the time. But personally this is the efficient way of doing this the test suggests in using `str` in place of `int`. But only `Int` has to be used. so the code looks good to me other than that. I personally feel this code is right and works.

Thanks and great job @Sranu2109

2021-05-14 10:11 UTC, sridhar-5 approved these changes
Code looks good to me. other than that failing test. if it's not a problem you can take it @ming-tsai

2021-05-14 10:35 UTC, ming-tsai requested changes
Hi @Sranu2109,
Please add your code on the readme of Python

2021-05-14 11:53 UTC, sridhar-5 commented
@ming-tsai ,I think the read me is now updated by @Sranu2109. can you check ?

2021-05-14 11:55 UTC, ming-tsai approved these changes

2021-05-14 11:56 UTC, ming-tsai commented
> @ming-tsai ,I think the read me is now updated by @Sranu2109. can you check ? 

Thanks

2021-05-14 11:58 UTC, ming-tsai requested changes
Hi @Sranu2109,
Could you check why Python GitHub action is failed?

2021-05-16 09:30 UTC, Sranu2109 commented
> Hi @Sranu2109,
> Could you check why Python GitHub action is failed?

You could use Pip-Installer from Github Actions to run package installation scripts, refer to this article [here](https://github.com/marketplace/actions/pip-installer).

It seems that the `mypy` package is missing from the build.

And/or you could add a `requirements.txt` top your project root and modify your `actions.yaml` to this.
```
steps:
- uses: actions/checkout@v2
- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.x'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt 
```

2021-05-16 10:56 UTC, sridhar-5 commented
can you add this import statement and update here if it works?.Not sure though just give it a try.

`from typing import Callable`

2021-05-16 11:00 UTC, sridhar-5 requested changes

2021-05-16 11:00 UTC, sridhar-5 commented on algorithms/Python/sorting/heap-sort.py
> +alist = list(map(int, alist))
And also try typecasting alist to int.

2021-05-16 11:01 UTC, sridhar-5 commented
If that didn't work. update here I'll find other ways.

2021-05-16 12:44 UTC, Arsenic-ATG reviewed
the python check was failing due to the bug in mypy where it fails to identify callable types. 

it is also reported as a bug on their repo, you can check that [here](https://github.com/python/mypy/issues/8117)

2021-05-16 17:30 UTC, sridhar-5 approved these changes
Nice Work @Sranu2109  This can be Merged @ming-tsai.

Thanks.

2021-05-16 17:30 UTC, Arsenic-ATG commented
the last 2 commits I did were minute changes which required to pass test cases, and the changes include :- 

1. Adding extra newline between import and rest of the code ( to pass isort check )

2. Adding automated test cases instead of using input() and thus removing the interactive element from the program making unit testing possible. ( to pass pytest check )

2021-05-16 17:32 UTC, ming-tsai approved these changes

2021-05-16 17:33 UTC, merged

2021-05-16 17:38 UTC, sridhar-5 commented
Great @Arsenic-ATG.

2021-05-16 17:39 UTC, ming-tsai commented
Nice team work