More optimized way of bubble-sort
MakeContributions/DSA pull request #321
Opened 2021-05-22 15:57 UTC by shivam-0510

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [x] New algorithm
- [x] Optimization in previous algorithms
- [x] Code style update
- [x] Refactor
- [x] Documentation
- [x] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-05-22 16:33 UTC, ming-tsai commented
> **What kind of change does this PR introduce?** (check at least one)
> 
> * [x]  Bugfix
> * [x]  New algorithm
> * [x]  Optimization in previous algorithms
> * [x]  Code style update
> * [x]  Refactor
> * [x]  Documentation
> * [x]  Other, please describe:
> 
> **Briefly describe the changes in this PR**
> 
> **Other information:**

Hi @shivam-0510,
Do not select all checklist, in your case, this is not a new algorithm and if you checked other please describe something

2021-05-22 17:03 UTC, shivam-0510 commented
Hi @ming-tsai ,
I had unmarked the unnecessary checklist.

2021-05-23 06:15 UTC, TawfikYasser requested changes

2021-05-23 06:15 UTC, TawfikYasser commented on algorithms/Java/sorting/bubble-sort.java
> +package JAVA;
Welcome @shivam-0510 

Thanks for the good work

Please remove this line `package JAVA;` as it is only required for your local project.

and please add some information about the new optimized algorithm in a multi-line comment.

2021-05-24 02:40 UTC, TawfikYasser approved these changes
Nice work @shivam-0510

2021-05-24 04:02 UTC, shivam-0510 commented
Thanks for the appreciation @TawfikYasser

2021-05-24 12:24 UTC, merged