code for length of LCS
MakeContributions/DSA pull request #322
Opened 2021-05-24 16:27 UTC by ssaumyaa7

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Implemented python code to give length of Longest Common Subsequence

**Other information:**
NA

2021-05-24 16:29 UTC, ssaumyaa7 commented
@Arsenic-ATG  @atin  @sridhar-5  @cyberwizard1001 

Length of Longest common subsequence in python

2021-05-25 03:29 UTC, cyberwizard1001 requested changes
Looked up the code, logic seems fine. However, you have to modify the naming conventions. According to pep-8, classes have continuous words identified by having the first letter as capital (which is fine) but functions are to be fully lowercase with every word separated by an underscore. Can you make sure the code follows convention?

@ming-tsai Is it possible to add this as a check?

2021-05-25 03:33 UTC, ssaumyaa7 commented
@cyberwizard1001 @ming-tsai is it good to go now ?

2021-05-25 04:01 UTC, sridhar-5 approved these changes
Nice Work @ssaumyaa7 . @ming-tsai we can take it forward.

Thanks

2021-05-25 04:02 UTC, sridhar-5 approved these changes

2021-05-25 11:45 UTC, ming-tsai commented on algorithms/Python/README.md
> +6. [Length of Longest Common Subsequence](strings/length_LCS.py)
Please rename the file name
```suggestion
6. [Longest Common Subsequence](strings/longest_common_subsequence.py)
```

2021-05-25 12:57 UTC, ming-tsai commented
Hi @sridhar-5 and @cyberwizard1001,
Please check it again, the last commit of @ssaumyaa7 is only rename the file's name

2021-05-25 15:00 UTC, sridhar-5 approved these changes
Code looks good to me @ming-tsai.
And file name is also following the organization's contribution guide lines I guess

2021-05-25 15:17 UTC, ming-tsai approved these changes

2021-05-25 15:17 UTC, merged

2021-05-25 15:21 UTC, sridhar-5 commented
Nice Work Guys. @ssaumyaa7 @ming-tsai @cyberwizard1001