chore(CPlusPlus): add avl tree
MakeContributions/DSA pull request #323
Opened 2021-05-25 11:35 UTC by Ashborn-SM

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Add avl tree

**Other information:**

2021-05-25 15:17 UTC, UG-SEP requested changes
Please kindly do the changes 
Feel free to ask doubt related to this PR

2021-05-25 15:17 UTC, UG-SEP commented on algorithms/CPlusPlus/Trees/avl.cpp
> +#include <iostream>
add the description about the program

2021-05-25 15:17 UTC, UG-SEP commented on algorithms/CPlusPlus/Trees/avl.cpp
> +	 */
use single line comment where as possible

2021-05-25 15:17 UTC, UG-SEP commented on algorithms/CPlusPlus/Trees/avl.cpp
> +	 */
```suggestion
	/*
	 * Create and insert the node in the appropriate place of the tree
	 * Update the height of every node in the tree
	 * Check the balance factor of the node and do the appropriate rotation
	 * To make the tree balanced
	 */
```

2021-05-25 15:17 UTC, UG-SEP commented on algorithms/CPlusPlus/Trees/avl.cpp
> +}
add time complexity of the program at the EOF

2021-05-26 06:07 UTC, UG-SEP approved these changes
thanks for contributing @Ashborn-SM

2021-05-26 11:12 UTC, ming-tsai approved these changes

2021-05-26 11:12 UTC, merged