Created anagram.cpp
MakeContributions/DSA pull request #336
Opened 2021-06-03 17:57 UTC by NegiAkash890

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Added anagram.cpp

2021-06-04 15:04 UTC, UG-SEP requested changes
Please kindly do the requested changes
Fell free to as any doubt related to this PR

2021-06-04 15:04 UTC, UG-SEP commented on algorithms/CPlusPlus/Strings/anagram.cpp
> +//Description : To check whether a string is anagram or not.
better to tell the method you used 
hint: count character method

2021-06-04 15:04 UTC, UG-SEP commented on algorithms/CPlusPlus/Strings/anagram.cpp
> +    return true;
use few comment where the code is hard to understand so it's become user friendly program

2021-06-06 17:06 UTC, UG-SEP commented
@NegiAkash890 any update???

2021-06-08 02:05 UTC, UG-SEP approved these changes
Thanks for contributing @NegiAkash890 
Great work😊
`The main thing which most impresses me was its clear cut user-friendly description of the program`

2021-06-08 10:39 UTC, ming-tsai approved these changes

2021-06-08 10:39 UTC, merged