Abundant Number
MakeContributions/DSA pull request #357
Opened 2021-06-14 14:09 UTC by UG-SEP

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Created a folder name: `Maths` in CSharp/src dir and added the solution.cs there
**Other information:**

closes: #355

2021-06-14 14:56 UTC, ming-tsai requested changes
Hi @UG-SEP,
I just add some comments about the coding style, please add a unit test for this and ensure this works on [dotnetfiddle NET 5](https://dotnetfiddle.net/).

2021-06-14 14:56 UTC, ming-tsai commented on algorithms/CSharp/src/Maths/abundant-number.cs
> +    {
Please fix the ident
```suggestion
        {
```

2021-06-14 14:56 UTC, ming-tsai commented on algorithms/CSharp/src/Maths/abundant-number.cs
> +        public static bool Abudant(int num)
Rename the method name to `IsAbudant`
```suggestion
        public static bool IsAbudant(int num)
```

2021-06-14 14:56 UTC, ming-tsai commented on algorithms/CSharp/src/Maths/abundant-number.cs
> +                return false;
Add the missing curly brackets
```suggestion
            if (sum > num)
            {
                return true;
            }
            else // it is not an abundant number
            {
                return false;
            }
```

2021-06-14 14:56 UTC, ming-tsai commented on algorithms/CSharp/src/Maths/abundant-number.cs
> +                Console.WriteLine($"{num} is not an abundant number");
Add the missing curly brackets

2021-06-15 03:11 UTC, UG-SEP commented
> Hi @UG-SEP,
> I just add some comments about the coding style, please add a unit test for this and ensure this works on [dotnetfiddle NET 5](https://dotnetfiddle.net/).

@ming-tsai I need to add a test unit in the test folder 
Am I right

2021-06-15 12:01 UTC, ming-tsai commented
> > Hi @UG-SEP,
> > I just add some comments about the coding style, please add a unit test for this and ensure this works on [dotnetfiddle NET 5](https://dotnetfiddle.net/).
> 
> @ming-tsai I need to add a test unit in the test folder 
> Am I right
> 

Yes

2021-06-16 07:10 UTC, UG-SEP commented
![Problem](https://user-images.githubusercontent.com/75884061/122173865-d692d100-ce9f-11eb-8304-ef106a7a2e9c.jpg)
@ming It is not showing to add a reference to the Abundant. cs well I have created this in the same project and also Installed NUnit & NUnit3 test adapter 
Can you please help me

2021-06-16 14:36 UTC, ming-tsai commented
> ![Problem](https://user-images.githubusercontent.com/75884061/122173865-d692d100-ce9f-11eb-8304-ef106a7a2e9c.jpg)
> @Ming It is not showing to add a reference to the Abundant. cs well I have created this in the same project and also Installed NUnit & NUnit3 test adapter
> Can you please help me

You could guide with [Palindrome test on C#](https://github.com/MakeContributions/DSA/blob/main/algorithms/CSharp/test/Strings/palindrome.cs)

2021-06-16 16:26 UTC, UG-SEP commented
![unittest](https://user-images.githubusercontent.com/75884061/122257235-7165cc80-ceed-11eb-919c-9529e1bb73d8.jpg)
All test cases pass successfully
Thanks, @ming-tsai  for helping me during the unit test work
I am too glad to have you with me...

2021-06-16 18:04 UTC, ming-tsai approved these changes

2021-06-16 18:05 UTC, merged

2021-06-16 18:05 UTC, ming-tsai commented
Nice work