chore(c++): add Reorder list
MakeContributions/DSA pull request #373
Opened 2021-06-24 07:27 UTC by UG-SEP

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added Reorder List program in Algorithm/Linked-Lists/Reorder-List

**Other information:**

closes: #363

2021-06-25 05:35 UTC, aayushjain7 requested changes

2021-06-25 05:35 UTC, aayushjain7 commented on algorithms/CPlusPlus/Linked-Lists/Reorder-List.cpp
> +    }
fix the indentation here.

2021-06-25 21:23 UTC, aayushjain7 requested changes

2021-06-25 21:23 UTC, aayushjain7 commented on algorithms/CPlusPlus/Linked-Lists/Reorder-List.cpp
> +    }
It still does not look right. Indent the code within the brackets

2021-06-26 07:47 UTC, aayushjain7 submitted a review, later dismissed
Great Work! I guess the indent problem is some GitHub issue.

2021-06-26 08:44 UTC, Arsenic-ATG commented
>  I guess the indent problem is some GitHub issue.

My guess is that it is due to inconsistent use of tabs and spaces in the program which are being differently rendered by OP's editor and the web-browser and ultimately messing up the indentation after pushing the changes to GitHub and being viewed from a different text editor.

This should be fixed after the commit [75a375](https://github.com/MakeContributions/DSA/pull/373/commits/75a375443c829a55ccbdd2615ffe8de1fed117b3)

2021-06-26 10:15 UTC, UG-SEP commented
> > I guess the indent problem is some GitHub issue.
> 
> My guess is that it is due to inconsistent use of tabs and spaces in the program which are being differently rendered by OP's editor and the web browser, messing up the indentation after pushing the changes to GitHub and being viewed from a different text editor.
> 
> This should be fixed after the commit [75a375](https://github.com/MakeContributions/DSA/pull/373/commits/75a375443c829a55ccbdd2615ffe8de1fed117b3)

I have a solution for this @Arsenic-ATG and @aayushjain7  as me and @Arsenic-ATG know Qt so we can create an application that removes extra indent from the program. Hope you understand what I want to say

2021-06-26 10:41 UTC, Arsenic-ATG commented
> > > I guess the indent problem is some GitHub issue.
> > 
> > 
> > My guess is that it is due to inconsistent use of tabs and spaces in the program which are being differently rendered by OP's editor and the web browser, messing up the indentation after pushing the changes to GitHub and being viewed from a different text editor.
> > This should be fixed after the commit [75a375](https://github.com/MakeContributions/DSA/pull/373/commits/75a375443c829a55ccbdd2615ffe8de1fed117b3)
> 
> I have a solution for this @Arsenic-ATG and @aayushjain7 as me and @Arsenic-ATG know Qt so we can create an application that removes extra indent from the program. Hope you understand what I want to say

I think the easiest method to fix it is to use a different text editor, and avoid mixing spaced and tabs with each other. Or if you are looking for an automated code formatter then you can use [this](https://codebeautify.org/cpp-formatter-beautifier) one.

2021-06-26 13:19 UTC, aayushjain7 approved these changes
Looks great now!! 💯

2021-06-26 14:59 UTC, merged