Added a C# linear search algorithm
MakeContributions/DSA pull request #393
Opened 2021-07-22 18:15 UTC by izzykreie

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added a new linear search algorithm (C#). Created unit tests for the algorithm and updated the README to reflect the newly added algorithm

**Other information:**

2021-07-22 19:55 UTC, ming-tsai requested changes
Hi @izzykreie,
I have add some comments, please check it out and let me know when you finished

2021-07-22 19:55 UTC, ming-tsai commented on algorithms/CSharp/src/Search/linear-search.cs
> +using System.Text;
Please remove unused `using`

2021-07-22 19:55 UTC, ming-tsai commented on algorithms/CSharp/src/Search/linear-search.cs
> +                Console.WriteLine("The number you are searching for is at index: " + indexOfSearchNumber);
Please add the missing curly bracket
```suggestion
            if (indexOfSearchNumber == -1)
            {
                Console.WriteLine("The number you are searching for does not exist in this list.");
            }
            else
            {
                Console.WriteLine("The number you are searching for is at index: " + indexOfSearchNumber);
            }
```

2021-07-22 19:55 UTC, ming-tsai commented on algorithms/CSharp/src/Search/linear-search.cs
> +            return -1;
Please add missing curly bracket and ensure only one `return` on this method

2021-07-22 19:55 UTC, ming-tsai commented on algorithms/CSharp/test/Search/linear-search.cs
> +using System.Text;
Please remove unused `using`

2021-07-22 19:55 UTC, ming-tsai commented on algorithms/CSharp/test/Search/linear-search.cs
> +        public void Should_Return_Index_Of_Matching_Element_In_Array(int searchNumber, int expectedIndexOfSearchTerm)
The method name is `InPutCodition_OutPutCodition` example `PassSearchNumber_ShouldGetExpectedIndex`

2021-07-22 19:55 UTC, ming-tsai commented on algorithms/CSharp/test/Search/linear-search.cs
> +        [Test]
This attribute is not necessarry

2021-07-23 12:50 UTC, izzykreie commented
@ming-tsai, thanks for reviewing my pull request! I made all of the requested changes. Please let me know if I need to make further adjustments to the code.

2021-07-23 13:35 UTC, ming-tsai approved these changes

2021-07-23 13:35 UTC, merged