chore(CPlusPlus): adding recursion programs
MakeContributions/DSA pull request #402
Opened 2021-07-29 13:51 UTC by jishanshaikh4

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR:**

Added following programs to the section ```algorithms/cpp/recursion```:
- GCD/HCF of two numbers
- Sum of all elements of an array
- Decimal number to Binary conversion
- Sum of digits of a decimal integer

**Other information:** Refer #395 and #347

2021-07-31 12:01 UTC, Arsenic-ATG requested changes
Thanks for the executable links with the programs.

I have left the review comments in the source itself ( some of them are nit picks ).

2021-08-07 07:57 UTC, jishanshaikh4 commented
@Arsenic-ATG Thank you for the review. Make appropriate changes as you like. It is allowed for maintainers.

2021-08-11 07:28 UTC, Arsenic-ATG commented
> @Arsenic-ATG Thank you for the review. Make appropriate changes as you like. It is allowed for maintainers.

If it would have been small nits or doc updates, I would have done that easily.
But some stuff here requires the creator's involvement ( especially decimal-too-binary.cpp ) where the change might involve refactoring the way program works altogether.

2021-08-14 23:02 UTC, ming-tsai commented
@jishanshaikh4, please solve the merge conflict

2021-08-18 10:34 UTC, juhi1999 commented
Hello I'm new to contribution.. and I wish to contribute codes...

2021-08-18 13:41 UTC, Arsenic-ATG commented
> Hello I'm new to contribution.. and I wish to contribute codes...

Greetings @juhi1999, 
In order to contribute, either pick up an [open issue](https://github.com/MakeContributions/DSA/issues) and start working on it, or directly send a PR implementing an algorithm or data-structure in a particular programming language, that is still not present in the repository. 

Also, do make sure to give the repo's [contribution guidelines](https://github.com/MakeContributions/DSA#contribution-guidelines) a good read, before making any contribution.

--- 

P.S. : 
Avoid sending messages in a pull request ( especially if the message is not related to the PR ), such messages create noise in the conversation. 
Kindly open a new issue or use [Discussions](https://github.com/MakeContributions/DSA/discussions) section for such queries.

2021-08-18 15:37 UTC, jishanshaikh4 commented
@ming-tsai Sorry for the untimely reply, I'm out of my place for a couple of weeks. I would resume as I get back.

2021-08-18 15:38 UTC, ming-tsai commented
> @ming-tsai Sorry for the untimely reply, I'm out of my place for a couple of weeks. I would resume as I get back.

Don't worries

2021-09-02 18:33 UTC, ming-tsai commented
Hi @jishanshaikh4,
Any update?

2021-09-10 14:11 UTC, jishanshaikh4 commented
> Hi @jishanshaikh4,
> Any update?

Yep, I'm all on it now.

2021-09-10 14:12 UTC, jishanshaikh4 commented on algorithms/CPlusPlus/Recursion/decimal-to-binary-conversion.cpp
> +// Tip: Use long long (and unsigned long long) instead
Sure thing. I added the comment to provide a bit for beginners.

2021-09-10 14:19 UTC, jishanshaikh4 commented on algorithms/CPlusPlus/Recursion/decimal-to-binary-conversion.cpp
> +        return (decimal_number%2 + 10*decimalToBinary(decimal_number/2));
Bug fixed.

2021-09-10 14:19 UTC, jishanshaikh4 commented on algorithms/CPlusPlus/Recursion/GCD-of-two-numbers.cpp
> +// There exists an inbuilt function for gcd also __gcd(T a, T b) with Template T
__gcd() still works in C++

2021-09-10 14:23 UTC, jishanshaikh4 commented on algorithms/CPlusPlus/Recursion/GCD-of-two-numbers.cpp
> +    cout << "GCD of " << n1 << " and " << n2 << " is " << gcd(n1, n2);
Sure thing. gcd() has been replaced to euclidean_gcd().

2021-09-10 14:31 UTC, jishanshaikh4 commented
@Arsenic-ATG Please review again.

2021-09-11 03:06 UTC, Arsenic-ATG approved these changes

2021-09-11 15:20 UTC, merged

2021-09-11 15:20 UTC, ming-tsai commented
Nice work!!!