chore(CPlusPlus): add Matrix Chain Multiplication to Dynamic Programming
MakeContributions/DSA pull request #410
Opened 2021-08-06 06:04 UTC by ptarafdar001

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-08-06 06:19 UTC, ptarafdar001 commented
It shows one conflict in **README.md** file, so how can I resolve it?

2021-08-06 12:36 UTC, Ashborn-SM commented
@ptarafdar001 i believe you have a merge conflict (not really sure about this).
Did you retrieve changes from the original repo to your remote repo? and did you pull those changes to your local repo before make this commit?

2021-08-06 14:15 UTC, ptarafdar001 commented
@Ashborn-SM  yeah, I forgot to sync my fork to the original repo. Now, what can I do to fix this issue?

2021-08-06 16:13 UTC, Ashborn-SM commented
this could help for syncing https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/
And `git pull` to update your local repo.
Although i'm not really sure this will work without a hitch, i'm also not sure this is the solution since i don't know what the actual problem is.

Maybe wait for @Arsenic-ATG, he can help

2021-08-07 02:26 UTC, Arsenic-ATG requested changes

2021-08-07 02:26 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Dynamic-Programming/matrix-chain-multiplication.cpp
> + * Explaination: The matrices have dimensions
Typo :
```suggestion
 * Explanation: The matrices have dimensions 
```

2021-08-07 02:26 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Dynamic-Programming/matrix-chain-multiplication.cpp
> + * Auxiliary Space: O(N2)
```suggestion
 * Time Complexity: O(N^3)
 * Auxiliary Space: O(N^2)
```

2021-08-07 02:26 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Dynamic-Programming/matrix-chain-multiplication.cpp
> +    int arr[n];
Avoid using variable length arrays ( VLAs ) in C++. Although some compilers ( like gcc ) support them as non-standard extension, they are not allowed by C++ standards so a compiler is not obligated to do so.

I see you are already using std::vector in your program then you should have not problem using it here also.

2021-08-07 02:26 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Dynamic-Programming/matrix-chain-multiplication.cpp
> +int matrixChainMulti(int arr[], int i, int j, vector<vector<int>> dp)
Is it really mandatory to copy vector `dp` every-time you pass it to the function ?

also I see you not are changing the value of `i` and `j` in the function, then wouldn't it be a good idea to make them const ?

```suggestion
int matrixChainMulti(int arr[],const int i,const int j, vector<vector<int>> &dp)
```

2021-08-08 02:21 UTC, Arsenic-ATG approved these changes

2021-08-09 12:55 UTC, merged