Added Digit DP section
MakeContributions/DSA pull request #417
Opened 2021-08-19 11:22 UTC by Masterroy1210

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Added  two Standard Digit Dynamic Programming problem in the DIGIT DP section

**Other information:**

2021-08-19 19:48 UTC, ming-tsai commented
Hi @Masterroy1210,
What is different between Dynamic Programming and Digit Dynamic Programing?

2021-08-19 19:52 UTC, Masterroy1210 commented
> Hi @Masterroy1210,
> What is different between Dynamic Programming and Digit Dynamic Programing?

Traditional dp is like memonizing the ans for overlapping substructure so that we do not calculate it again 
But  in digit dp we jst make required number by putting a digit one by one and keep track using flags

2021-08-20 06:08 UTC, aayushjain7 requested changes

2021-08-20 06:08 UTC, aayushjain7 commented on algorithms/CPlusPlus/Digit Dynamic Programming/Digit-dp-2.cpp
> +
Correct the spelling for Recusrsive.

2021-08-20 06:08 UTC, aayushjain7 commented on algorithms/CPlusPlus/Digit Dynamic Programming/Digit-dp-2.cpp
> +    //limit should be nums[index];
change greated to greater.

2021-09-05 19:29 UTC, ming-tsai commented
Hi @Masterroy1210,
Any updated?

2021-09-21 12:43 UTC, ming-tsai commented
Hi @Masterroy1210,
This pull request will be closed, any updates please re-open this pull request.

2021-09-21 12:43 UTC, closed without merging