chore(CSharp): added algorithm to determine factorial
MakeContributions/DSA pull request #437
Opened 2021-08-29 19:50 UTC by Waqar-107

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Added a new algorithm (C#) for determining the factorial of a number. Created unit tests for the algorithm and updated the README to reflect the newly added algorithm

**Other information:**

2021-09-02 18:39 UTC, ming-tsai requested changes
Hi @Waqar-107,
Sorry for late, here is a suggestion for this pull request

2021-09-02 18:39 UTC, ming-tsai commented on algorithms/CSharp/src/Algorithms.csproj
> +    <StartupObject>Algorithms.Recursion.Factorial</StartupObject>
Please rollback this change

2021-09-03 07:22 UTC, Waqar-107 commented on algorithms/CSharp/src/Algorithms.csproj
> +    <StartupObject>Algorithms.Recursion.Factorial</StartupObject>
@ming-tsai done.

2021-09-03 14:42 UTC, ming-tsai approved these changes

2021-09-03 14:42 UTC, merged