Minnimum swaps to make elements less than K together
MakeContributions/DSA pull request #439
Opened 2021-08-30 10:41 UTC by Shivang-Konde

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
I have added code to find out how many minimum swaps are needed to make all elements which are less than K together . 

**Other information:**

2021-09-02 13:44 UTC, UG-SEP requested changes
Please kindly add your program name and link in c++ [readme.md](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/README.md)
If you have any doubt regarding this PR free to ask 😊
as well as one more thing that renames the file name from 
Minimum_swaps_to_make_elements_less_than_k_together.cpp to minimum-swaps-and-k-together.cpp

2021-09-02 13:44 UTC, UG-SEP commented on algorithms/CPlusPlus/Arrays/Minimum_swaps_to_make_elements_less_than_k_together.cpp
> +
Add the time complexity and a test-case example

2021-09-02 13:44 UTC, UG-SEP commented on algorithms/CPlusPlus/Arrays/Minimum_swaps_to_make_elements_less_than_k_together.cpp
> +        cin>>k;
print user-friendly info that what to enter 
> i.e. cout<<"Enter the number of test cases ";

2021-09-05 19:31 UTC, ming-tsai commented
Hi @Shivang-Konde,
Any updated?

2021-09-21 12:46 UTC, ming-tsai commented
Hi @Shivang-Konde,
This pull request will be closed, any updates please re-open this pull request.

2021-09-21 12:46 UTC, closed without merging