chore(C): add doubly linked list
MakeContributions/DSA pull request #456
Opened 2021-09-09 14:33 UTC by Ashborn-SM

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
add doubly linked list using C

**Other information:**

2021-09-17 04:27 UTC, Ashborn-SM commented
@UG-SEP waiting for your review

2021-09-17 17:50 UTC, aayushjain7 requested changes

2021-09-17 17:50 UTC, aayushjain7 commented on algorithms/C/linked-lists/doubly-linked-list.c
> +
provide aim/description for the program

2021-09-17 17:50 UTC, aayushjain7 commented on algorithms/C/linked-lists/doubly-linked-list.c
> +}
also, provide 1-2 test cases with time and space complexity

2021-09-20 11:36 UTC, aayushjain7 approved these changes
great work!

2021-09-20 11:41 UTC, merged