Add maximum difference
MakeContributions/DSA pull request #464
Opened 2021-09-14 12:07 UTC by khushisinha20

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

This program finds the maximum difference between two elements in an array such that larger element appears after the smaller number in C++.

**Other information:**

2021-09-17 17:48 UTC, aayushjain7 requested changes

2021-09-17 17:48 UTC, aayushjain7 commented on algorithms/CPlusPlus/Arrays/maximum-difference.cpp
> +	int maxDiff = a[1] - a[0];					//Initialized maximum difference with the differnce between first and second value
correct difference spelling.

2021-09-21 12:54 UTC, ming-tsai commented
Hi @khushisinha20,
Any updated?

2021-09-22 16:57 UTC, aayushjain7 approved these changes
LGTM🔥

2021-09-22 17:55 UTC, merged