Algorithm to equalize the array
MakeContributions/DSA pull request #465
Opened 2021-09-14 15:27 UTC by Tanmoy07tech

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Algorithm name is Equalize the array . I implement this algorithm with python programming
**Other information:**

2021-09-15 13:17 UTC, atin commented
Implementation looks good! Though you can change the variable names a bit to make it more readable for eg. `freq` (or `frequency`) instead of `hast_table` and similarly for `max_hash_table`

Also you can shorten the code by using some built-in python functions, though its completely your choice
```python
def equalizeArray(arr):
    mode = max(arr, key=arr.count)    # element with max number of occurrence in the array i.e. mode of array
    num_mode = arr.count(mode)
    deletions = len(arr) - num_mode
    return deletions
```

2021-09-15 13:25 UTC, atin requested changes

2021-09-15 13:25 UTC, atin commented on algorithms/Python/arrays/equalize_the_array.py
> +import sys
@Tanmoy07tech You can remove these imports since these are not used in the code.

2021-09-15 13:28 UTC, atin commented on algorithms/Python/arrays/equalize_the_array.py
> +import sys
P.S. - Also add this file in [README.md](https://github.com/MakeContributions/DSA/blob/main/algorithms/Python/README.md)

2021-09-21 13:23 UTC, ming-tsai commented
Hi @Tanmoy07tech,
Any updated?

2021-09-30 19:43 UTC, closed without merging

2021-09-30 19:44 UTC, ming-tsai commented
Hi @Tanmoy07tech,
This pull request is closed due to is inactive, any update please re-open the pr