docs: add heap sort
MakeContributions/DSA pull request #471
Opened 2021-09-20 14:12 UTC by Gigolino2001

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

- Added the documentation of heap sort algorithm.
- Added the link of heap sort documentation to README.md.

**Other information:**

2021-09-20 18:51 UTC, ming-tsai requested changes
Hi @Gigolino2001,
Nice work, only a suggestion for this changes

2021-09-20 18:51 UTC, ming-tsai commented on docs/en/Sorting/Heap-Sort.md
> +3. **Applications:** Finding the order in statistics, dealing with priority queues in Prim's algorithm and Huffman enconding or data compression.
```suggestion
3. **Applications:** Finding the order in statistics, dealing with priority queues in Prim's algorithm and Huffman encoding or data compression.
```

2021-09-20 21:30 UTC, Gigolino2001 commented
> Hi @Gigolino2001,
> Nice work, only a suggestion for this changes

Sorry for that, thank you :)

2021-09-21 01:44 UTC, ming-tsai approved these changes

2021-09-21 01:44 UTC, merged