C++ program on string: to remove occurence of characters of 2nd string from the 1st string
MakeContributions/DSA pull request #475
Opened 2021-09-21 16:21 UTC by samughodake

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-09-21 16:55 UTC, ming-tsai commented
Hi @samughodake,
Does this pull request is the same change for #468?

2021-09-22 02:42 UTC, Ashborn-SM requested changes
@samughodake you can tell me if i am mistaken.

2021-09-22 02:42 UTC, Ashborn-SM commented on algorithms/CPlusPlus/Strings/remove-occurences.cpp
> +    //checking if the character of 2nd string is present in the 1st string
I believe you mean `checking the characters of the 1st string is present in the 2nd string`.
In line 15 you are looping through `s1` and in line 17 you are checking if the characters of 1st string is present
in `s2`, if you interchange those variables the end result will be different.
```suggestion
    //checking if the character of the 1st string is present in the 2nd string
```

2021-09-22 02:57 UTC, Ashborn-SM approved these changes

2021-09-22 04:32 UTC, samughodake commented
Thanks a lot! @Ashborn-SM 
should I update the readme file now?

2021-09-22 04:34 UTC, Ashborn-SM commented
> Thanks a lot! @Ashborn-SM
> should I update the readme file now?

Yes, totally forgot about that mb

2021-09-22 04:45 UTC, samughodake commented
> > Thanks a lot! @Ashborn-SM
> > should I update the readme file now?
> 
> Yes, totally forgot about that mb

will update the readme,thanks.

2021-09-22 06:25 UTC, Ashborn-SM approved these changes
Good job!!

2021-09-22 06:39 UTC, samughodake commented
> Good job!!

Thanks. Please merge this branch

2021-09-22 06:42 UTC, samughodake reviewed
Thanks for fixing typo errors

2021-09-22 06:45 UTC, Ashborn-SM approved these changes

2021-09-22 14:17 UTC, merged