add palindrome
MakeContributions/DSA pull request #483
Opened 2021-09-24 19:59 UTC by kumarsyadav2

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

adding a program to find palindrome number or string in c++
**Other information:**

2021-09-25 08:32 UTC, kumarsyadav2 commented
Why this didn't merged yet? If there's any problem then kindly let me know...
Did I have made pull request/issue in correct way or any it can be made into some other good ways...?

2021-09-25 09:08 UTC, ming-tsai commented
> Why this didn't merged yet? If there's any problem then kindly let me know...
> Did I have made pull request/issue in correct way or any it can be made into some other good ways...?

We have to wait @UG-SEP to review this pull request

2021-09-26 00:15 UTC, ming-tsai commented
Hi @kumarsyadav2,
If @UG-SEP does not response tomorrow I will assign another reviewer

2021-09-26 00:20 UTC, ming-tsai commented
Hi @kumarsyadav2,
Please add a reference to these files:
- [en](https://github.com/kumarsyadav2/DSA/blob/main/docs/en/Strings/Palindrome.md)
- [zh-tw](https://github.com/kumarsyadav2/DSA/blob/main/docs/zh-tw/Strings/Palindrome.md)
- [ja](https://github.com/kumarsyadav2/DSA/blob/main/docs/ja/Strings/Palindrome.md)

2021-09-26 07:01 UTC, kumarsyadav2 commented
> Hi @kumarsyadav2,
> Please add a reference to these files:
> 
> * [en](https://github.com/kumarsyadav2/DSA/blob/main/docs/en/Strings/Palindrome.md)
> * [zh-tw](https://github.com/kumarsyadav2/DSA/blob/main/docs/zh-tw/Strings/Palindrome.md)
> * [ja](https://github.com/kumarsyadav2/DSA/blob/main/docs/ja/Strings/Palindrome.md)

Hi, i only know english language, i didn't understand file's language that is mentioned above!
also i am bit beginner in open source i.e. i don't know what reference to add in above files and how?
if there's any documentation or readme file that expalins what and how to add reference then kindly share with me... or guide me how to do. i will definitely add reference to these files.

2021-09-26 09:49 UTC, ming-tsai commented
> > Hi @kumarsyadav2,
> > Please add a reference to these files:
> > 
> > * [en](https://github.com/kumarsyadav2/DSA/blob/main/docs/en/Strings/Palindrome.md)
> > * [zh-tw](https://github.com/kumarsyadav2/DSA/blob/main/docs/zh-tw/Strings/Palindrome.md)
> > * [ja](https://github.com/kumarsyadav2/DSA/blob/main/docs/ja/Strings/Palindrome.md)
> 
> Hi, i only know english language, i didn't understand file's language that is mentioned above!
> also i am bit beginner in open source i.e. i don't know what reference to add in above files and how?
> if there's any documentation or readme file that expalins what and how to add reference then kindly share with me... or guide me how to do. i will definitely add reference to these files.
> 

Ok, don't worries I will added another language by myself

2021-09-26 10:24 UTC, kumarsyadav2 commented
Let me try, whether i can do that or not.
initially it seems that i can't do this but after reading some **docs** and online stuff, it seems i can do that

2021-09-27 08:25 UTC, kumarsyadav2 commented
@ming-tsai kindly assign it active reviewer/member!!! They are not responding from last 3 days.

2021-09-27 08:36 UTC, aayushjain7 requested changes

2021-09-27 08:36 UTC, aayushjain7 commented on algorithms/CPlusPlus/Maths/palindrome.cpp
> +int main()
provide description for program

2021-09-27 08:36 UTC, aayushjain7 commented on algorithms/CPlusPlus/Maths/palindrome.cpp
> +}
provide test cases and time complexity

2021-09-27 11:25 UTC, kumarsyadav2 reviewed
Hey @aayushjain7 , I added description, comments, time complexities and test-cases in code as comments.

2021-09-28 17:55 UTC, aayushjain7 approved these changes
nice!

2021-09-28 18:47 UTC, merged