added new array program
MakeContributions/DSA pull request #508
Opened 2021-10-02 05:34 UTC by samughodake

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-10-02 07:33 UTC, Capt-Madhan submitted a review, later dismissed

2021-10-03 05:11 UTC, Ashborn-SM requested changes
@samughodake please do the changes mentioned.

2021-10-04 04:19 UTC, samughodake commented
Hello, @Ashborn-SM 
I made all the desired changes.
Thanks.

2021-10-04 05:57 UTC, Ashborn-SM commented on algorithms/CPlusPlus/Arrays/search-insert-position.cpp
> +    cout<<"The target element can be inserted at: "<<searchInsert(nums,target);
The text here can be misleading as it prints `The target element can be inserted at: (some_index)` regardless of whether the target is present or not.

You don't want to print this if the target is present, in such cases a valid statement will be 
`The location of the target is (some_index)`.

My suggestion is to have a valid statement for both the cases(when the target is present & when the target is not present), you can make changes in the function itself accordingly.

2021-10-04 06:01 UTC, Ashborn-SM approved these changes
Good Work!!

2021-10-04 12:36 UTC, merged