chore(CPlusPlus): add prefix sum
MakeContributions/DSA pull request #624
Opened 2021-10-27 13:24 UTC by Deeps-01

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-10-30 07:32 UTC, aayushjain7 requested changes
Also, update the readme.MD file

2021-10-30 07:32 UTC, aayushjain7 commented on algorithms/CPlusPlus/Arrays/prefix_sum_algorithm_implementation.cpp
> +
fix indentation.

2021-10-30 07:32 UTC, aayushjain7 commented on algorithms/CPlusPlus/Arrays/prefix_sum_algorithm_implementation.cpp
> +     }
fix indentation.

2021-10-30 07:32 UTC, aayushjain7 commented on algorithms/CPlusPlus/Arrays/prefix_sum_algorithm_implementation.cpp
> +
Add examples/test-cases with time complexity

2021-11-23 18:50 UTC, ming-tsai commented
Hi @Deeps-01,
Any updates?

2021-12-27 14:03 UTC, ming-tsai commented
Hi @Deeps-01,
This pull request will be closed when making a change please re-open this pull request.

2021-12-27 14:03 UTC, closed without merging