Create max-min-avg.cpp
MakeContributions/DSA pull request #631
Opened 2021-11-07 19:10 UTC by manekasingh05

Maximum, Minimum and average in an array

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2021-11-07 19:12 UTC, manekasingh05 commented
Mximum, minimum and average

2021-11-08 16:55 UTC, aayushjain7 requested changes
update readme.MD file also

2021-11-08 16:55 UTC, aayushjain7 commented on algorithms/CPlusPlus/Arrays/max-min-avg.cpp
> +}
fix indentation.

2021-11-08 17:27 UTC, manekasingh05 reviewed
Please review changes

2021-11-12 08:25 UTC, aayushjain7 requested changes
update readme.MD file also

2021-11-23 18:52 UTC, ming-tsai commented
Hi @manekasingh05,
Any updates?

2021-11-23 19:04 UTC, manekasingh05 commented
> Hi @manekasingh05,
> Any updates?

I have already updated readme.Md file as per the instructions it was mentioned to add in the same file in the form of comments. Do I need to make separate file and keep both of these files in a folder?

2021-11-23 20:03 UTC, ming-tsai commented
> > Hi @manekasingh05,
> > Any updates?
> 
> I have already updated readme.Md file as per the instructions it was mentioned to add in the same file in the form of comments. Do I need to make separate file and keep both of these files in a folder?

You should modify on your branch `manekasingh05:patch-3` and the readme.md is on `CPlusPlus` folder

2022-01-13 13:03 UTC, ming-tsai commented
Hi @manekasingh05,
Any update?

2022-01-13 13:22 UTC, manekasingh05 commented
> Hi @manekasingh05,
> Any update?

Yes, updated Readme.md. You can check now!

2022-01-17 16:29 UTC, aayushjain7 approved these changes

2022-01-17 18:30 UTC, ming-tsai commented on algorithms/CPlusPlus/README.md
> +- [Maximum Minimum Average of numbers](max-min-avg.cpp)
Please fix the link
```suggestion
- [Maximum Minimum Average of numbers](Arrays/max-min-avg.cpp)
```

2022-01-17 18:32 UTC, ming-tsai approved these changes

2022-01-17 18:37 UTC, merged