Stack-Queue Implemenatation
MakeContributions/DSA pull request #639
Opened 2021-11-21 23:24 UTC by underager

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Following algorithm has been implemented in Javascript
1. Stack Implementation
2. Queue Implementation
3. Stack using two queue implementation

**Other information:**
Reference Issue : #638

2021-11-23 18:56 UTC, ming-tsai commented on algorithms/JavaScript/README.md
> +- [Queue Implementation](src/Queue/queueImpl.js)
Hi @underager,
Please rename the folder name to plural and lowercase and the file name as a suggestion.
```suggestion
## Stack
- [Stack Implementation](src/stacks/stack.js)
- [Stack Using Two Queue](src/stacks/two-stack.js)

## Queue
- [Queue Implementation](src/queues/queue.js)
```

2021-11-26 18:03 UTC, ming-tsai commented
Hi @underager,
Are you finished modifying?

2021-11-26 21:53 UTC, underager commented
> 

Yes I have renamed the directory and file as suggested and the same is reflected in the latest commit, please let me know if there is anything else, thank you.

2021-11-27 18:03 UTC, ming-tsai requested changes
Hi @underager,
Please delete these file

2021-11-27 18:03 UTC, ming-tsai commented on algorithms/JavaScript/src/queue/queueImpl.js
> +class Node {
Please delete this file

2021-11-27 18:03 UTC, ming-tsai commented on algorithms/JavaScript/src/stack/stackImpl.js
> +class Stack {
Please delete this file

2021-11-27 18:03 UTC, ming-tsai commented on algorithms/JavaScript/src/stack/usingTwoQueue.js
> +// Implement Stack using two queues
Please delete this file

2021-11-27 18:03 UTC, ming-tsai commented on algorithms/JavaScript/README.md
> +- [Queue Implementation](src/Queue/queueImpl.js)
Update the reference @underager

2021-11-28 03:47 UTC, underager commented on algorithms/JavaScript/src/queue/queueImpl.js
> +class Node {
This file has been deleted.

2021-11-28 03:49 UTC, underager commented on algorithms/JavaScript/src/stack/stackImpl.js
> +class Stack {
This file has been deleted.

2021-11-28 03:50 UTC, underager commented on algorithms/JavaScript/src/stack/usingTwoQueue.js
> +// Implement Stack using two queues
This file has been deleted

2021-11-28 03:53 UTC, underager commented
I hope the latest commits take care of everything. Sorry for inconvenience.

2021-12-02 18:39 UTC, ming-tsai approved these changes

2021-12-02 18:39 UTC, merged