BFS, DFS Algorithm in C added
MakeContributions/DSA pull request #644
Opened 2021-12-01 13:18 UTC by AnishLohiya

**PR Checklist:**
- [X] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [X] My addition does not have a spelling problem
- [X] My submission has a proper and user-friendly description of the algorithm
- [X] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Added Breadth-first search and Depth First Search Algorithm in C. 

**Other information:**

2021-12-05 06:10 UTC, UG-SEP commented
Sorry @ming-tsai I can't check it right know my exam are going on
Please give to another reviewer
🙏

2021-12-06 12:30 UTC, Ashborn-SM requested changes

2021-12-07 03:33 UTC, Ashborn-SM requested changes
Don't use acronym and capital letters, follow the [naming convention](https://github.com/MakeContributions/DSA/blob/main/README.md#1-contribution-specifications) used in the repo.
Also update the `README.md`

2021-12-07 03:33 UTC, Ashborn-SM commented on algorithms/C/graphs/DFS.c
> +                DFSTraversal(G, j, n);
missing out brackets could possibly lead to bug that would be difficult to find.
```suggestion
            if (G[start][j] == 1 && visited[j] == 0){
                DFSTraversal(G, j, n);
            }
```

2021-12-07 14:08 UTC, Ashborn-SM requested changes
Fix the typo in the name of the file

Change `breath-first-search.c` `breadth-first-search.c`

2021-12-08 03:11 UTC, Ashborn-SM reviewed
Write the output of the program at the end of the file

2021-12-08 08:22 UTC, Ashborn-SM approved these changes
Good Work!!

2021-12-08 14:18 UTC, merged