chore(CPlusPlus): add return string subsequences
MakeContributions/DSA pull request #677
Opened 2022-01-20 16:00 UTC by vivekthedev

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Return String Subsequences using Recursion

**Other information:**

2022-01-25 04:57 UTC, Arsenic-ATG requested changes

2022-01-25 04:57 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Recursion/string-subsequences.cpp
> +#include <iostream>
```suggestion
#include <iostream>
#include <string>
```

Make sure to include all the required headers, even though some implementations include string header which implementing parts of iostream, but they are not obligated to do so.

2022-01-25 04:57 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Recursion/string-subsequences.cpp
> +    string *out = new string[1000];
what if the number of substrings is more than 1000 ?

An alternative here would be to use a flexible container ( like std::vector ) and let it do the heavy lifting of memory management while you take care of this program.

2022-01-26 13:14 UTC, Arsenic-ATG commented
Along with changes suggested, make sure you also update the required README.md index of Cplusplus dir with your creation in it.

2022-02-23 13:16 UTC, ming-tsai commented
Hi @vivekthedev,
Any update?

2022-03-24 15:12 UTC, closed without merging