Add linked list functionalities
MakeContributions/DSA pull request #700
Opened 2022-02-12 17:47 UTC by banerjeesoumya15

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [x] Other, please describe:

**Briefly describe the changes in this PR**
Added insertion and deletion functionality in Linked List, in Python.

**Other information:**

2022-02-13 14:38 UTC, banerjeesoumya15 commented
Can anyone please approve this PR? Or explain me how I can make this better?

2022-02-13 18:25 UTC, banerjeesoumya15 commented
Hi,

I've made necessary changes to the code. Let me know if any more change needs to be fixed.

2022-02-15 11:17 UTC, Arsenic-ATG requested changes

2022-02-15 11:17 UTC, Arsenic-ATG commented on algorithms/Python/linked_lists/singly.py
> +        Delete first occurence of given data
typo caught by code-spell : occurence ==> occurrence

```suggestion
        Delete first occurrence of given data
```

2022-02-16 02:03 UTC, Arsenic-ATG commented on algorithms/Python/linked_lists/singly.py
> +    ll.deleteData(1)
What if the element that is to be deleted doesn't exist in the list ?

2022-02-20 03:00 UTC, Arsenic-ATG approved these changes

2022-02-21 19:28 UTC, merged