Add number system
MakeContributions/DSA pull request #714
Opened 2022-03-09 18:37 UTC by nk412k

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-03-11 03:52 UTC, nk412k commented on algorithms/CPlusPlus/Number system/.gitignore
> +.vscode/
done

2022-03-26 08:25 UTC, Arsenic-ATG requested changes
every addition of an algorithm should also accompany a change updating the corresponding index README.md file (CPlusPlus/README.md).

2022-03-26 08:25 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp
> +}
typos detected by codespell 

```
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:5: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:6: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:7: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:8: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:11: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:12: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:19: multipler ==> multiplier, multiple
./algorithms/CPlusPlus/Number system/decimal_to_hexa.cpp:20: multipler ==> multiplier, multiple
```

```suggestion
string decimal_to_hexa(int n){
    int multiplier=1;
    while(multiplier<=n)
        multiplier*=16;
    multiplier/=16;
    string num="";
    int d;
    while(multiplier>=1){
        d=n/multiplier;
        if(d>9){
            char c='A'+(d-10);
            num= num + c;
        }
        else
        num=num + to_string(d);
        n=n-(d*multiplier);
        multiplier/=16;
    }
    return num;
}
```

2022-03-29 07:00 UTC, Arsenic-ATG commented
now the only thing left is updating the proper readme and this should be good to go

2022-03-29 08:09 UTC, Arsenic-ATG approved these changes

2022-03-29 12:45 UTC, merged