Add minima maxima
MakeContributions/DSA pull request #730
Opened 2022-03-31 22:26 UTC by mheidari988

**PR Checklist:**
- [ x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [ x] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

Minima Maxima is a searching algorithm to find local and global minima and maxima in a list of numbers

**Other information:**

2022-04-05 12:37 UTC, ming-tsai requested changes
Hi @mheidari988,
I had added some suggestions to this pull request.

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +using System.Text;
Remove unused `using`

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +                Console.WriteLine($"Local Maxima: {n}");
Add missing curly brackets
```suggestion
            foreach (var n in lmins)
            {
                Console.WriteLine($"Local Minima: {n}");
            }

            foreach (var n in lmaxs)
            {
                Console.WriteLine($"Local Maxima: {n}");
            }
```

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +        }
Add missing curly brackets
```suggestion
        public static List<int> GetLocalMinima(List<int> numbers)
        {
            var result = new List<int>();

            if (numbers.Count < 3)
            {
                result.Add(numbers.Min());
            }
            else
            {
                // Check first element
                if (numbers[0] < numbers[1])
                {
                    result.Add(numbers[0]);
                }

                //Loop middle elements
                for (int i = 1; i < numbers.Count - 1; i++)
                {
                    if (numbers[i - 1] >= numbers[i] && numbers[i] <= numbers[i + 1])
                    {
                        result.Add(numbers[i]);
                    }
                }

                //Check last elements
                if (numbers[^1] < numbers[^2])
                {
                    result.Add(numbers[^1]);
                }
            }

            return result;
        }

        public static List<int> GetLocalMaxima(List<int> numbers)
        {
            var result = new List<int>();

            if (numbers.Count < 3)
            {
                result.Add(numbers.Max());
            }
            else
            {
                // Check first element
                if (numbers[0] > numbers[1])
                {
                    result.Add(numbers[0]);
                }
                    
                //Loop middle elements
                for (int i = 1; i < numbers.Count - 1; i++)
                {
                    if (numbers[i - 1] <= numbers[i] && numbers[i] >= numbers[i + 1])
                    {
                        result.Add(numbers[i]);
                    }
                }

                //Check last elements
                if (numbers[^1] > numbers[^2])
                {
                    result.Add(numbers[^1]);
                }
            }

            return result;
        }
```

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/test/Search/minima-maxima.cs
> +        public void MinimaMaxima_GetListOfMinimas(int[] input, int[] result)
Rename the method name
```suggestion
        public void PassIntegerList_ShouldGetExpectedMinimas(int[] input, int[] result)
```

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/test/Search/minima-maxima.cs
> +        public void MinimaMaxima_GetListOfMaximas(int[] input, int[] result)
Rename the method name
```suggestion
        public void PassIntegerList_ShouldGetExpectedMaximas(int[] input, int[] result)
```

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +        public static List<int> GetLocalMaxima(List<int> numbers)
Rename the method name
```suggestion
        public static List<int> FindMaximas(List<int> numbers)
```

2022-04-05 12:37 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +        public static List<int> GetLocalMinima(List<int> numbers)
Rename the method
```suggestion
        public static List<int> FindMinimas(List<int> numbers)
```

2022-04-05 16:33 UTC, mheidari988 commented
Thanks

2022-04-05 18:10 UTC, ming-tsai requested changes
Hi @mheidari988,
I forgot to comment on this suggestion.

2022-04-05 18:10 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +            }
Please call the method with a new name
```suggestion
            var minimas= FindMinimas(numbers);
            var maximas= FindMaximas(numbers);

            foreach (var minima in minimas)
            {
                Console.WriteLine($"Local Minima: {minima}");
            }

            foreach (var maxima in maximas)
            {
                Console.WriteLine($"Local Maxima: {maxima}");
            }
```

2022-04-07 14:18 UTC, ming-tsai commented on algorithms/CSharp/src/Search/minima-maxima.cs
> +            var maximas= FindMaximas(numbers);
```suggestion
            var minimas = FindMinimas(numbers);
            var maximas = FindMaximas(numbers);
```

2022-04-07 14:19 UTC, ming-tsai commented on algorithms/CSharp/test/Search/minima-maxima.cs
> +            var expected1 = MinimaMaxima.GetLocalMaxima(input.ToList());
```suggestion
            var expected1 = MinimaMaxima.FindMaximas(input.ToList());
```

2022-04-07 14:23 UTC, ming-tsai approved these changes

2022-04-07 14:27 UTC, merged