Updated README and added a new file
MakeContributions/DSA pull request #740
Opened 2022-04-16 00:10 UTC by maty714

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Character_Limit allows a user to enter a string and determine how many characters in that string will be shown before it continues with periods. For example, entering in "Hello" and limiting the character limit to 2 will out put "He..."

**Other information:**

2022-04-16 19:17 UTC, Waqar-107 commented on algorithms/CSharp/src/Strings/character-limit.cs
> +using System.Text.RegularExpressions;
remove the unused imports

2022-04-16 19:18 UTC, Waqar-107 commented on algorithms/CSharp/src/Strings/character-limit.cs
> +            int num = Convert.ToInt32(Console.ReadLine());
This will throw an exception if someone enters more than 1 integer. For example, someone enters "5 7 9"

2022-04-16 19:20 UTC, Waqar-107 commented on algorithms/CSharp/src/Strings/character-limit.cs
> +
remove these lines  please

2022-04-16 19:20 UTC, Waqar-107 commented on algorithms/CSharp/src/Strings/character-limit.cs
> +
remove these lines please

2022-04-16 19:21 UTC, Waqar-107 commented on algorithms/CSharp/src/Strings/character-limit.cs
> +
please keep  a single line here to maintain consistency

2022-04-16 19:26 UTC, Waqar-107 requested changes
I have addressed some issues, please resolve them. When you are done, please mention me in the comments. I am not sure if I get a notification when you will request a re-review.

Please write test cases. You will find them written for the other algorithms. If you need ideas about what test to write then you can write the followings,

1. Code catches the exception and shows a proper error message.
2. 2-3 valid inputs give proper output.

Finally, add the time complexity of your algorithm. If you get stuck then feel free to ask for clarifications 🙂

2022-04-19 01:40 UTC, maty714 commented
Quick question. In regards to time complexity. Is this something that needs to be added in the code (which gives an output in ms) or description (linear time)?

2022-04-19 16:29 UTC, maty714 commented
@Waqar-107 Ok so I fixed the changes, but it appears it failed a test. I tried looking through this, but could not figure this out. Apologies as I am new...

2022-04-19 18:18 UTC, Waqar-107 commented
> @Waqar-107 Ok so I fixed the changes, but it appears it failed a test. I tried looking through this, but could not figure this out. Apologies as I am new...

@maty714 no worries, looking into it.

2022-04-19 18:36 UTC, Waqar-107 commented
@ming-tsai according to my understanding, codespell detects common spelling mistakes in the code. Here it has considered `Hel` as misspelled but it is a part of the test case. Any idea how to make it avoid checking testcases?

![image](https://user-images.githubusercontent.com/24852360/164072128-ebf5b3d6-5e2f-4bc5-86f6-32a8fc42d06f.png)
![image](https://user-images.githubusercontent.com/24852360/164072463-4eef2745-e8f9-4d03-bcae-0be54c7f8b7d.png)

2022-04-19 18:37 UTC, Waqar-107 approved these changes
Looks good 🔥

2022-04-19 18:57 UTC, ming-tsai commented
> @ming-tsai according to my understanding, codespell detects common spelling mistakes in the code. Here it has considered `Hel` as misspelled but it is a part of the test case. Any idea how to make it avoid checking testcases?
> 
> ![image](https://user-images.githubusercontent.com/24852360/164072128-ebf5b3d6-5e2f-4bc5-86f6-32a8fc42d06f.png)
> ![image](https://user-images.githubusercontent.com/24852360/164072463-4eef2745-e8f9-4d03-bcae-0be54c7f8b7d.png)
> 
> 

I will check it out.

2022-04-20 13:50 UTC, ming-tsai requested changes
Hi @maty714,
I have added some suggestions for this pull request.

2022-04-20 13:50 UTC, ming-tsai commented on algorithms/CSharp/src/Strings/character-limit.cs
> +}
Please format the ciode
```suggestion
using System;
using System.Linq;

//Time Complexity: O(N)
namespace Algorithms.Strings
{
    public class TextHelper
    {
        public static void Main()
        {
            Console.WriteLine("Please enter a string");
            string input = Console.ReadLine();

            while (input == "")
            {
                Console.WriteLine("Please enter a string");
                input = Console.ReadLine();
            }

            Console.WriteLine("Please enter the number of characters you want to show");
            string input2 = Console.ReadLine();

            while (!input2.All(char.IsDigit) || input2.All(char.IsWhiteSpace))
            {
                Console.WriteLine("The number you have entered is invalid. Please try again:");
                input2 = Console.ReadLine();
            }

            int num = Convert.ToInt32(input2);
            Console.WriteLine(Character_Limit(input, num));
        }

        //Limits the the amount of characters shown in a string.
        public static string Character_Limit(string input, int num)
        {
            //converts a string to a character array
            char[] ch = input.ToCharArray();

            //loops through the array from the last element to the first, and replaces each element with a "."
            for (int i = ch.Count(); i > num; i--)
            {
                ch[i - 1] = '.';
            }

            //converts character array back to string to be returned by the method
            string output = new string(ch);
            return output;
        }
    }
}
```

2022-04-20 13:50 UTC, ming-tsai commented on algorithms/CSharp/test/Strings/character-limit.cs
> +            Assert.IsTrue(result == expected, "error");
Please use `Assert.AreEqual`
```suggestion
            Assert.AreEqual(expected, result);
```

2022-04-20 13:50 UTC, ming-tsai commented on algorithms/CSharp/test/Strings/character-limit.cs
> +
Please remove the space
```suggestion
```

2022-04-20 13:50 UTC, ming-tsai commented on algorithms/CSharp/README.md
> +- [Character-Limit](src/Strings/character-limit.cs)
Please remove `-` on the title of the option
```suggestion
- [Character Limit](src/Strings/character-limit.cs)
```

2022-04-21 03:45 UTC, maty714 commented
@ming-tsai Just committed the suggestions. Third time is a charm!

2022-04-21 13:28 UTC, ming-tsai requested changes

2022-04-21 13:28 UTC, ming-tsai commented on algorithms/CSharp/src/Strings/character-limit.cs
> +        public static string Character_Limit(string input, int num)
Rename the method name
```suggestion
        public static string CharacterLimit(string input, int num)
```

2022-04-21 13:28 UTC, ming-tsai commented on algorithms/CSharp/src/Strings/character-limit.cs
> +            Console.WriteLine(Character_Limit(input, num));
Rename the method name
```suggestion
            Console.WriteLine(CharacterLimit(input, num));
```

2022-04-21 13:38 UTC, ming-tsai approved these changes

2022-04-21 13:38 UTC, merged