Add folder structure for Spanish translations and Quick Sort
MakeContributions/DSA pull request #793
Opened 2022-08-08 00:06 UTC by brugner

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [x] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Add folder structure for Spanish translations and the explanation for the Quick Sort algorithm.

2022-08-09 02:46 UTC, ming-tsai requested changes
Hi @brugner,
There are some suggestions for the pull request.

2022-08-09 02:46 UTC, ming-tsai commented on docs/es/README.md
> +
You could remove these due to we don't have the documentation about theses sections.
```suggestion
```

2022-08-09 02:46 UTC, ming-tsai commented on docs/es/Ordenamiento/Quick-Sort.md
> +
We have implementation of quick sort on `C` language.
```suggestion
- [C](../../../algorithms/C/sorting/quick-sort.c)
```

2022-08-09 18:27 UTC, brugner commented
Hi @ming-tsai, I've just commited your suggestions. Thanks!

2022-08-10 21:15 UTC, ming-tsai approved these changes

2022-08-10 21:16 UTC, merged