Add Quick Sort implementation for CSharp
MakeContributions/DSA pull request #798
Opened 2022-08-11 03:12 UTC by brugner

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
Add Quick Sort implementation for C#.

2022-08-11 18:51 UTC, ming-tsai requested changes
Hi @brugner,
Some suggestions for the pull request:
1. Modify the `README.md` file on the path `/algorithms/CSharp` and add `quick-sort.cs` file on the index.
2. Add quick sort unit test on this file `/algorithms/CSharp/test/Sorts`

2022-08-11 18:51 UTC, ming-tsai commented on algorithms/CSharp/src/Sorts/quick-sort.cs
> +                Console.Write($"{array[i]} ");
Please add missing curly brackets
```suggestion
            for (int i = 0; i < array.Length; i++)
            {
                Console.Write($"{array[i]} ");
            }
```

2022-08-12 03:07 UTC, brugner commented on algorithms/CSharp/src/Sorts/quick-sort.cs
> +                Console.Write($"{array[i]} ");
Fixed!

2022-08-12 12:39 UTC, ming-tsai approved these changes

2022-08-12 12:39 UTC, merged