prim algo completed
MakeContributions/DSA pull request #816
Opened 2022-08-23 17:04 UTC by angshudas

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-08-23 17:06 UTC, angshudas commented
Leave any suggestions if any.

2022-08-26 12:55 UTC, Arsenic-ATG requested changes

2022-08-26 12:55 UTC, Arsenic-ATG commented on algorithms/CPlusPlus/Graphs/prim's_algorithm.cpp
> +  cout<<primAlgorithm();
what if I call this function more than one time in `main ()` ?

2022-08-31 06:48 UTC, Arsenic-ATG approved these changes

2022-09-01 15:39 UTC, merged