add-new-file
MakeContributions/DSA pull request #818
Opened 2022-08-25 06:28 UTC by zaksandra

**PR Checklist:**
- [ x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ x] My addition is on refer on the language README.md file
- [x ] My addition does not have a spelling problem
- [ x] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-08-27 20:04 UTC, mohitchakraverty reviewed
This looks fine which only checks for sparse matrix or not but also if you can add its triple form representation because representing a sparse matrix by a 2D array leads to wastage of lots of memory as zeroes in the matrix are of no use in most of the cases. So, instead of storing zeroes with non-zero elements, we create triples- (Row, Column, value) in which we only store non-zero elements. And instead, use this for different purposes.

2022-08-28 15:04 UTC, zaksandra commented
@mohitchakraverty thank you for reviewing, I'll add the triple form representation as well.

2022-08-31 06:52 UTC, Arsenic-ATG requested changes
Please also update the proper README.md with your program in the index. 


for your case, it would be [algorithms/CPlusPlus/README.md](https://github.com/ssandra102/DSA/blob/add-new-code/algorithms/CPlusPlus/README.md).

2022-09-01 11:55 UTC, Arsenic-ATG approved these changes

2022-09-01 11:58 UTC, Arsenic-ATG approved these changes

2022-09-01 12:42 UTC, merged