chore(Java): add next greater element
MakeContributions/DSA pull request #833
Opened 2022-09-05 13:29 UTC by Ishantgarg-web

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-09-10 15:34 UTC, mohitchakraverty requested changes
Also, add documentation in the code for better understanding

2022-09-10 15:34 UTC, mohitchakraverty commented on algorithms/Java/stacks/Next_Greater_Element.java
> +              System.out.print(arr[i]+" ");
You are printing the same input array please fix that

2022-09-11 03:53 UTC, Ishantgarg-web commented
Hi @mohitchakraverty I do some changes and remove unnecessary code.

2022-09-11 13:32 UTC, mohitchakraverty approved these changes

2022-09-11 13:32 UTC, merged