Add anagram
MakeContributions/DSA pull request #834
Opened 2022-09-05 13:33 UTC by Ishantgarg-web

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-09-09 19:52 UTC, ming-tsai requested changes

2022-09-09 19:52 UTC, ming-tsai commented on algorithms/Java/README.md
>  - [Celebrity Problem](stacks/celebrity-problem.java)
Please remove this file change

2022-09-09 19:52 UTC, ming-tsai commented on algorithms/Java/stacks/Next_Greater_Element.java
> + * Given an array arr[] of size N having distinct elements, the task is to find the next greater element for each element of the array in order of their appearance in the array.
Please remove this file change

2022-09-10 07:50 UTC, Ishantgarg-web commented
I remove all unnecessary changes..
Now, please review it

2022-09-10 17:36 UTC, ayo-ajayi approved these changes
It was nicely done.
Thank you.

2022-09-11 19:44 UTC, ming-tsai approved these changes

2022-09-11 19:45 UTC, merged

2022-09-11 20:36 UTC, ayo-ajayi commented
I noticed that the package name is "main". It should be changed to "string" since the anagram.go file is in the "string" package.

2022-09-11 23:10 UTC, ming-tsai commented
> I noticed that the package name is "main". It should be changed to "string" since the anagram.go file is in the "string" package.
> 
> Also, the main function should be given another name. But make sure the name is written in PascalCase so that it can be exported for use in another package.
> 
> This is a package that should be called by another program.

@ayo-ajayi, could you make a new pull request for enhancement?

2022-09-11 23:50 UTC, ayo-ajayi commented
> 

done