Singly Circular LinkedList
MakeContributions/DSA pull request #848
Opened 2022-09-25 12:18 UTC by riteshyadav27

Singly Circular LinkedList with functionality of Add, Add in front, Display, Reverse , Search element in LinkedList

2022-09-25 12:29 UTC, Parsh092 approved these changes

2022-09-25 12:29 UTC, Parsh092 submitted a review, later dismissed

2022-09-26 03:59 UTC, riteshyadav27 commented
> Thanks for opening this pull request! Please check out our contributing guidelines.
> 

I checked that and all requirements were done.

2022-09-27 10:53 UTC, riteshyadav27 commented
I have added BFS and DFS code for graph traversal in java.

2022-09-27 13:43 UTC, mohitchakraverty requested changes
Please also update the respective README.md file
In your case, it will be algorithms/Java/README.md

2022-09-27 14:13 UTC, riteshyadav27 commented
I updated the README.md file for circular singly linked list in Linked List Section , BFS and DFS in Graph Section .

2022-10-05 06:00 UTC, mohitchakraverty requested changes
Please add more documentation to your code that helps users understand better.

2022-10-12 05:01 UTC, riteshyadav27 commented
I have added the Output of all programs with their proper input .

2022-10-12 06:02 UTC, mohitchakraverty requested changes
- Please make different PRs for different algorithm
- In naming the file, replace underscore with dashes
- Change the name circularll to circular-singly-linkedlist
- Also add comments to your code explaining what or how your code is working

2022-10-12 11:52 UTC, riteshyadav27 commented
Updated Readme.md file, changed file name, explanation added for circular-singly-linkedlist having reverse(), addfront(), search() functions with Output

2022-10-13 03:59 UTC, riteshyadav27 commented
@mohitchakraverty will you please add hacktoberfest 2022 label 🙌

2022-10-15 06:02 UTC, riteshyadav27 commented
@mohitchakraverty I didn't understand why codespell is failed . Will you please help me what is it and how it works .

2022-10-15 15:44 UTC, mohitchakraverty requested changes
Also fix the spelling error in DSA/algorithms/CPlusPlus/Arrays/max-subarray-sum.cpp
At line line 23 : Approach

Then you are good to go and your code will pass all the test.

2022-10-15 15:44 UTC, mohitchakraverty commented on algorithms/Java/linked-lists/circular-singly-linkedlist.java
> +// Here intial linkedlist was 9 5 8 7 1 2 and after using reverse function the linkedlist become 2 1 7 8 5 9
```suggestion
// Here initial linkedlist was 9 5 8 7 1 2 and after using reverse function the linkedlist become 2 1 7 8 5 9
```

2022-10-16 06:26 UTC, riteshyadav27 commented
@mohitchakraverty Done. I updated both the files.

2022-10-16 07:24 UTC, mohitchakraverty approved these changes

2022-10-16 07:25 UTC, mohitchakraverty commented
Great work! Thanks

2022-10-16 07:25 UTC, merged