Algorithms/Java/Maths/permutation_sequences.java
MakeContributions/DSA pull request #872
Opened 2022-10-01 15:39 UTC by Abhishek109062

Added a new java file in Algorithms/Java/Maths/permutation_sequences.java

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
- I have added new Algorithm
- Name - Permutation-Sequence
- Language - Java
- You can practice this algorithm online [Permutation-Sequence](https://leetcode.com/problems/permutation-sequence/)

**Other information:**

2022-10-01 17:02 UTC, Abhishek109062 commented
PLs review the new algorithm that i have added

2022-10-06 06:18 UTC, mohitchakraverty requested changes
Please fix the typo and make the following changes

2022-10-06 06:18 UTC, mohitchakraverty commented on algorithms/Java/Maths/permutation_sequence.java
> +k = k - (index from pervious) * (n-2)! = k - 0 * (n - 2)! = 1 - 0 = 1;
```suggestion
k = k - (index from previous) * (n-2)! = k - 0 * (n - 2)! = 1 - 0 = 1;
```

2022-10-06 06:18 UTC, mohitchakraverty commented on algorithms/Java/Maths/permutation_sequence.java
> +k = k - (index from pervious) * (n - 3)! = k - 1 * (4 - 3)! = 1 - 1 = 0;
```suggestion
k = k - (index from previous) * (n - 3)! = k - 1 * (4 - 3)! = 1 - 1 = 0;
```

2022-10-06 06:20 UTC, mohitchakraverty commented
Also update your branch **Abhishek109062:Permutation-Sequence** with **MakeContributions:main** to pass all the test cases

2022-10-07 14:44 UTC, mohitchakraverty approved these changes
Great work !

2022-10-07 14:44 UTC, merged