Added Check-Even-Odd Algo
MakeContributions/DSA pull request #876
Opened 2022-10-02 04:54 UTC by en1gm479

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [x] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**
I have added the Algorithm to check for Even and Odd numbers in CplusPlus. I've added two methods for checking Even-Odd, one through Logical And operator (&) and other through Mod operator(%). 

This issue (#501) has been open for a long time and I have decided to close it by making this PR.

2022-10-02 05:40 UTC, en1gm479 commented
Spell corrected (sting->string) in algorithms/Java/Maths/roman-numerals.java which leads to failing of codepsell workflow.

2022-10-03 18:30 UTC, en1gm479 commented
@ming-tsai please review the PR

2022-10-04 11:28 UTC, en1gm479 commented
@mohitchakraverty @ming-tsai please review the PR.

2022-10-05 05:57 UTC, mohitchakraverty requested changes
Update your branch en1gm479:add-CheckEvenOdd with the recent changes done to MakeContributions:main
Then all the test cases will be passed.

2022-10-05 05:57 UTC, mohitchakraverty commented on algorithms/Java/Maths/roman-numerals.java
> + *      The input string should contain only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M').
No need of making changes to this file. Its already fixed and merge

2022-10-05 08:35 UTC, mohitchakraverty approved these changes

2022-10-05 08:35 UTC, mohitchakraverty commented
Great work !

2022-10-05 08:36 UTC, merged