Redundant parenthesis in cpp completed
MakeContributions/DSA pull request #946
Opened 2022-10-06 07:04 UTC by dev24il

**PR Checklist:**
- [x] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [] My addition is on refer on the language README.md file
- [x] My addition does not have a spelling problem
- [x] My submission has a proper and user-friendly description of the algorithm
- [x] My submission has the time complexity of the algorithm
- [x] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

## Table of Content
- RedundantParenthesis

## RedundantParenthesis
Given a string of balanced expression, find if it contains a redundant parenthesis or not. A set of parenthesis are redundant if the same sub-expression is surrounded by unnecessary or multiple brackets. Print True if redundant, else False.
Note: Expression may contain ‘+‘, ‘*‘, ‘–‘ and ‘/‘ operators. Given expression is valid and there are no white spaces present.
For example:
- ((a+b)) can reduced to (a+b), this is Redundant
- (a+b*(c-d)) doesn't have any redundant or multiple
brackets

## Terms Explained:
### Stack : Stack is a linear data structure which follows a particular order in which the operations are performed. The order may be LIFO(Last In First Out) or FILO(First In Last Out).
![image](https://media.geeksforgeeks.org/wp-content/cdn-uploads/gq/2013/03/stack.png)

Redundant : The expression should not have extra brackets.

## Algorithm
### We will use stack as a data structure to solve this problem.
1. We iterate through the given expression and for each character in the expression, if the character is an open parenthesis ‘(‘ or any operators, we push it to the stack.
2. If the character is close parenthesis ‘)’, then pop characters from the stack till matching open parenthesis ‘(‘ is found. 
For any sub-expression of expression, if we are able to pick any sub-expression of expression surrounded by (), then we again left with () as part of string, we have redundant braces. 
We iterate through the given expression and for each character in the expression, if the character is an open parenthesis ‘(‘ or any of the operators or operands, we push it to the stack. If the character is close parenthesis ‘)’, then pop characters from the stack till matching open parenthesis ‘(‘ is found. 
Now for redundancy two condition will arise while popping- 
1. If immediate pop hits an open parenthesis ‘(‘, then we have found a duplicate parenthesis. For example, (((a+b))+c) has duplicate brackets around a+b. When we reach the second “)” after a+b, we have “((” in the stack. Since the top of stack is an opening bracket, we conclude that there are duplicate brackets. 

2. If immediate pop doesn’t hit any operand(‘*’, ‘+’, ‘/’, ‘-‘) then it indicates the presence of unwanted brackets surrounded by expression. For instance, (a)+b contain unwanted () around a thus it is redundant. 

**Other information:**

## Properties
### Time Complexity: O(n)
- Only one traversal of the loop is needed.
### Space Complexity: O(n)
- There is extra space required.

## Advantages
- Problem is solved in O(N) time complexity.
- Stack made it easier to understand.

## Disadvantages
- There is extra space required.

2022-10-07 12:36 UTC, dev24il commented
@Ashad001 please review this pr

2022-10-07 19:49 UTC, Ashad001 requested changes
Great Work @dev24il. Just add the reference of your code in this [readme](https://github.com/MakeContributions/DSA/blob/main/algorithms/CPlusPlus/README.md)

2022-10-07 20:00 UTC, dev24il commented
Added the reference in readme @Ashad001

2022-10-08 06:16 UTC, Ashad001 commented
I m afraid you haven't pushed the commit of readme. Have a look

2022-10-08 09:12 UTC, dev24il commented
@Ashad001 please review my pr

2022-10-08 09:14 UTC, Ashad001 approved these changes
Great Work! Keep Contributing

2022-10-08 09:19 UTC, merged