Create Kruskal's_Algorithm.py
MakeContributions/DSA pull request #993
Opened 2022-10-08 18:43 UTC by Purvesh77

Kruskal’s algorithm to find the minimum cost spanning tree uses the greedy approach. The Greedy Choice is to pick the smallest weight edge that does not cause a cycle in the MST constructed so far.

Time Complexity: O(ElogE) or O(ElogV), Sorting of edges takes O(ELogE) time. After sorting, we iterate through all edges and apply the find-union algorithm. The find and union operations can take at most O(LogV) time. So overall complexity is O(ELogE + ELogV) time. The value of E can be at most O(V2), so O(LogV) is O(LogE) the same. Therefore, the overall time complexity is O(ElogE) or O(ElogV)
Auxiliary Space: O(V + E), where V is the number of vertices and E is the number of edges in the graph

**PR Checklist:**
- [ ] My submission is formatted according to the guidelines in the [contributing guide](https://github.com/MakeContributions/DSA#contribution-guidelines)
- [ ] My addition is on refer on the language README.md file
- [ ] My addition does not have a spelling problem
- [ ] My submission has a proper and user-friendly description of the algorithm
- [ ] My submission has the time complexity of the algorithm
- [ ] My submission has sample input-output of the program (NOT FOR PYTHON)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] New algorithm
- [ ] Optimization in previous algorithms
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [ ] Other, please describe:

**Briefly describe the changes in this PR**

**Other information:**

2022-10-08 18:48 UTC, ming-tsai commented
Hi @Purvesh77,
This is the correct one?

2022-10-08 18:50 UTC, Purvesh77 commented
@ming-tsai If U are able to merge it
Then Merge it else,I will not understanding it automatically closing PR.

2022-10-08 18:52 UTC, ming-tsai commented
Hi @Purvesh77,
Ok, please wait the reviewer check the pull request.

2022-10-08 18:54 UTC, Purvesh77 commented
@ming-tsai What was the issue?

2022-10-08 18:57 UTC, ming-tsai commented
@Purvesh77 I don't know, but I just re-open it.

2022-10-09 11:56 UTC, Arsenic-ATG requested changes
please also update corresponding index README.md file with link to your algorithm in it.

2024-03-10 22:00 UTC, closed without merging